spring:
  profiles:
    active: dev # 默认的profile文件名称
  server:
    port: 8080

  data: #SpringData的相关配置
    redis: #redis的相关配置
      host: 192.168.88.135
      port: 6379
      username: default
      password: xia123
      database: 0
      connect-timeout: 200 #连接超时时间
      lettuce: #采用lettuce的开发组件
        pool:
          max-active: 200
          max-idle: 20
          min-idle: 10
          max-wait: 100 #最大等待时间100ms
          time-between-eviction-runs: 2000 #每2s回收一次空闲连接

logging:
  level:
    root: info #全局日志级别
    com.maker: debug #局部日志级别

#session相关配置
server:
  servlet:
    session:
      timeout: 30m